export interface User {
    ID: number;
    name: string;
    passwd: string;
    Prompt: string;
    answer: string;
    truename: string;
    idnumber: string;
    email: string;
    mobilenumber?: string;
    province?: string;
    city?: string;
    phonenumber?: string;
    address?: string;
    postalcode?: string;
    gender?: number;
    birthday?: Date;
    creatime: Date;
    qq?: string;
    passwd2?: string;
};